Iter9
apetsko/shortugo pull request #13
Opened 2024-12-24 14:56 UTC by apetsko

2025-01-04 08:28 UTC, zhark0vv commented
`BadRequestHandler` не используется по проекту.

2025-01-04 08:36 UTC, zhark0vv requested changes

2025-01-04 08:36 UTC, zhark0vv commented on internal/logging/zap.go
> +	once.Do(func() {
А зачем `once`? Ты же не вызываешь его из нескольких горутин.

2025-01-04 08:36 UTC, zhark0vv commented on internal/logging/zap.go
> +var instance *ZapLogger
Global-state, стоит вернуть инстанс наружу, но не определять его здесь.

2025-01-04 08:36 UTC, zhark0vv commented on internal/handlers/handlers.go
> +type Logger interface {
Не уверен, что это не лишнее.
Логгер смело можно "таскать" по приложению по реализации, т.к. он обычно не абстрагируется и не мокается.

2025-01-04 08:36 UTC, zhark0vv commented on internal/handlers/handlers.go
> +	fmt.Println(ID)
Что-то лишнее. :)

2025-01-04 08:36 UTC, zhark0vv commented on internal/middleware/compress.go
> +var zlogger, _ = logging.NewZapLogger()
Тут свой логгер, лучше переиспользовать тот, что инициализируется в main, передав его в конструктор, собирающий mw.

2025-01-04 08:36 UTC, zhark0vv commented on internal/middleware/compress.go
> +		buf := &bytes.Buffer{}
new(...)

2025-01-04 15:43 UTC, apetsko commented on internal/logging/zap.go
> +	once.Do(func() {
убрал

2025-01-04 15:43 UTC, apetsko commented on internal/logging/zap.go
> +var instance *ZapLogger
переделал

2025-01-04 15:43 UTC, apetsko commented on internal/handlers/handlers.go
> +type Logger interface {
убрал

2025-01-04 15:45 UTC, apetsko commented on internal/middleware/compress.go
> +		buf := &bytes.Buffer{}
сделано

2025-01-04 15:45 UTC, apetsko commented on internal/middleware/compress.go
> +var zlogger, _ = logging.NewZapLogger()
переделал

2025-01-04 15:45 UTC, apetsko commented on internal/handlers/handlers.go
> +	fmt.Println(ID)
убрал

2025-01-04 16:54 UTC, zhark0vv approved these changes

2025-01-04 16:54 UTC, zhark0vv commented on internal/logging/zap.go
>  	var err error
Эту аллокацию можно убрать.

2025-01-05 16:32 UTC, apetsko commented on internal/logging/zap.go
>  	var err error
странно но тут ничего и нет

2025-01-05 16:54 UTC, merged