Iter5
apetsko/shortugo pull request #6
Opened 2024-12-04 16:57 UTC by apetsko

2024-12-05 17:51 UTC, zhark0vv commented
Все зависимости в проекте от реализаций. Рекомендую использовать интерфейсные типы при инъекции зависимостей.
По расположению интерфейсов можно посмотреть [ролик](https://www.youtube.com/watch?v=eYHCCht8eX4).

2024-12-05 17:52 UTC, zhark0vv requested changes

2024-12-05 17:52 UTC, zhark0vv commented on cmd/client/client.go
> +	fmt.Println("Введите длинный URL")
В задании не было необходимости делать клиентский код, я бы рекомендовал убрать этот компонент из основного репозитория.

2024-12-05 17:52 UTC, zhark0vv commented on cmd/client/client_test.go
> +package main
Пустой файл.

2024-12-05 17:52 UTC, zhark0vv commented on internal/config/config.go
> +func Parse() config {
Публичный метод возвращает приватный инстанс, так лучше не делать.
Внутренние методы возвращают приватные сущности, публичные - публичные.

2024-12-05 17:52 UTC, zhark0vv commented on internal/config/config.go
> +		log.Fatal(err)
1. else после return;
2. Фаталить лучше на точке входа, а тут отдавать ошибку, иначе дебаг сильно усложняется.

2024-12-05 17:52 UTC, zhark0vv commented on internal/config/config.go
> +		fmt.Fprintf(flag.CommandLine.Output(), "Wrong params: baseUrl: %q, host: %q", c.BaseURL, c.Host)
Логгера достаточно.

2024-12-05 17:52 UTC, zhark0vv commented on internal/handlers/handlers.go
> +	fmt.Fprintf(w, "%s", shortenURL)
`w.Write()` читается несколько привычнее.

2024-12-05 17:52 UTC, zhark0vv commented on internal/server/server.go
> +func StartServer(address string, router *chi.Mux) {
Лучше, если сервер будет структурой, содержащей `address` и `router`, вместо того, чтобы принимать их в функции. Так у тебя будет конкретный сервер, инкапсулированный от другой логики.

2024-12-05 17:52 UTC, zhark0vv commented on internal/server/server.go
> +		log.Fatalf("server error: %s", err.Error())
Фаталить лучше только на точке входа.

2024-12-05 17:52 UTC, zhark0vv commented on internal/storage/inmem/inmem.go
> +func (im InMemStorage) Put(URL string) (ID string, err error) {
Лучше по поинтеру, иначе каждый вызов генерит новый инстанс `InMemStorage `

2024-12-05 17:52 UTC, zhark0vv commented on internal/storage/inmem/inmem_test.go
> +func Test_New(t *testing.T) {
Тестировать конструкторы - это лишнее. :)

2024-12-05 17:52 UTC, zhark0vv commented on internal/utils/utils.go
> +	ID = "EwHXdJfB"
Нужно убрать хардкод и сделать логику генерации уникальный идентификаторов для URL.

2024-12-06 16:58 UTC, apetsko commented on cmd/client/client.go
> +	fmt.Println("Введите длинный URL")
Удалил. в задании не было но там в примерах где то было написано добавить, ну я и добавил, хотя и мне не понятно зачем клиент тут.

2024-12-06 16:58 UTC, apetsko commented on cmd/client/client_test.go
> +package main
удалил

2024-12-06 16:58 UTC, apetsko commented on internal/config/config.go
> +func Parse() config {
принято, поправил

2024-12-06 16:59 UTC, apetsko commented on internal/config/config.go
> +		log.Fatal(err)
1. поправил
2. это вызов как раз на точке входа был, я подумал main будет почище без if err != nil{ log.Fatal(err)}. Обычно делают с обраткой ошибок на точке входа да?

2024-12-06 17:00 UTC, apetsko commented on internal/config/config.go
> +		fmt.Fprintf(flag.CommandLine.Output(), "Wrong params: baseUrl: %q, host: %q", c.BaseURL, c.Host)
удалил, это недостижимое условие, там по умолчанию проставятся значения из флагов

2024-12-06 17:18 UTC, apetsko commented on internal/server/server.go
> +func StartServer(address string, router *chi.Mux) {
поправил

2024-12-06 17:18 UTC, apetsko commented on internal/server/server.go
> +		log.Fatalf("server error: %s", err.Error())
поправил

2024-12-06 17:18 UTC, apetsko commented on internal/storage/inmem/inmem.go
> +func (im InMemStorage) Put(URL string) (ID string, err error) {
поправил

2024-12-06 17:19 UTC, apetsko commented on internal/storage/inmem/inmem_test.go
> +func Test_New(t *testing.T) {
поправил

2024-12-06 18:16 UTC, apetsko commented on internal/utils/utils.go
> +	ID = "EwHXdJfB"
сделал

2024-12-07 06:06 UTC, apetsko commented on internal/handlers/handlers.go
> +	fmt.Fprintf(w, "%s", shortenURL)
Исправил

2024-12-07 06:36 UTC, zhark0vv commented on internal/config/config.go
> +		log.Fatal(err)
_Обычно делают с обраткой ошибок на точке входа да_ - да, так проще дебажить паники.

2024-12-07 06:39 UTC, zhark0vv approved these changes

2024-12-07 06:39 UTC, zhark0vv commented on internal/utils/utils.go
> +	hash := sha256.Sum256([]byte(URL))
Уже лучше. :)
Но я не уверен, что не будет коллизий на большом количестве ссылок.

Задание со * - написать тест, который сделает 1000 вызовов для разных ссылок и убедиться, что хеши разные.

2024-12-07 06:41 UTC, zhark0vv approved these changes

2024-12-07 06:41 UTC, zhark0vv commented on internal/repositories/repositories.go
> +type Storage interface {
Стоит присмотреться к интерфейсам по месту реализации, как я писал тут:

https://github.com/apetsko/shortugo/pull/6#issuecomment-2521055793

2024-12-07 06:59 UTC, apetsko commented on internal/utils/utils.go
> +	hash := sha256.Sum256([]byte(URL))
Да спасибо сегодня сделаю

2024-12-07 07:00 UTC, apetsko commented on internal/repositories/repositories.go
> +type Storage interface {
Да странно что в мобильной версии его видел а по ом за компом почему то пропустил его. Тоже сегодня поправлю

2024-12-07 12:01 UTC, apetsko commented on internal/utils/utils.go
> +	hash := sha256.Sum256([]byte(URL))
тесты запилил, на 10_000_000 нет повторений

2024-12-07 12:13 UTC, apetsko commented on internal/repositories/repositories.go
> +type Storage interface {
repositories грохнул перенес интерфейс в handlers, спасибо

2024-12-09 12:45 UTC, merged

2025-11-27 18:12 UTC, apetsko commented
Владислав привет, выйди на связь)